//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_63132835.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [Display(Name = "Mã Khách Hàng")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage ="{0} Không được để rổng!")]
        public int MaKH { get; set; }
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        [Display(Name = "Tên Khách hàng ")] //dùng để đặt tên lại cho tên sách
        public string HoTen { get; set; }
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        [Display(Name = "Tài Khoản")] //dùng để đặt tên lại cho tên sách
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật khẩu")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        public string MatKhau { get; set; }
        [Display(Name = "Email")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        public string DiaChi { get; set; }
        [Display(Name = "Điện thoại")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        public string DienThoai { get; set; }
        [Display(Name = "Giới tính")] //dùng để đặt tên lại cho tên sách
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày sinh")] //dùng để đặt tên lại cho tên sách
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "{0} Không được để rổng!")]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
