//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_63132835.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ThamGias = new HashSet<ThamGia>();
        }
        [Display(Name ="Mã sách")] // dùng ?? ??t tên l?i cho c?t
    
        public int MaSach { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public string TenSach { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public string MoTa { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public string AnhBia { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public int MaNXB { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public int MaChuDe { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách
        public Nullable<int> Moi { get; set; }
        [Display(Name = "Tên sách")] //dùng ?? ??t tên l?i cho tên sách

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
