//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_63132835.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGia
    {
        public string VaiTro { get; set; }
        public string ViTri { get; set; }
        public int MaSach { get; set; }
        public int MaTacGia { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
